### ISSUE TITLE
Sometimes, rcload led_proc_init.soc failed.

### ISSUE THREAD

**Issue by appleCh** [Azure/SONiC#155] opened 2018-03-09 03:54 UTC
According to https://github.com/Azure/sonic-buildimage/blob/master/platform/broadcom/docker-syncd-brcm/start.sh,
Broadcom LED microprocessor init file led_proc_init.soc will be loaded until syncd has created the socket for bcmcmd to connect to,
but we find sometimes the led_proc_init.soc can not be load successed.

We have checked the following two point.
1. "getreg CMIC_LEDUP0_PROGRAM_RAM", led porg does not writte to CMIC_LEDUP0_PROGRAM_RAM register.
2. Print result message by 2>&1, such as
   "rcload ${PLATFORM_DIR}/led_proc_init.soc" >> apple_log.txt 2>&1, 
   when led_proc_init.c load success, we can see  
   "drivshell>rcload /usr/share/sonic/platform/led_proc_init.soc
	drivshell>",
   when led_proc_init.c load fail, the result message is "ending connection: Success".

After boot up and find led_proc_init.c load fail, we issue bcmcmd "rcload /usr/share/sonic/platform/led_proc_init.soc" again, 
the port led work well.
   
Do you have any suggestion, thanks.

**Attach debug file `sudo generate_dump`:**
[sonic_dump_sonic_20180309_112834.tar.gz](https://github.com/Azure/SONiC/files/1795574/sonic_dump_sonic_20180309_112834.tar.gz)
    **Output of `show version`:**
admin@sonic:~$ show version
SONiC Software Version: SONiC.master.0-dirty-20180308.064647
Distribution: Debian 8.10
Kernel: 3.16.0-5-amd64
Build commit: 33d5a9c
Build date: Thu Mar  8 06:59:08 UTC 2018
Built by: apple@CRAN-Server

Docker images:
REPOSITORY                 TAG                              IMAGE ID            SIZE
docker-syncd-brcm          latest                           27083bff537a        331.5 MB
docker-syncd-brcm          master.0-dirty-20180308.064647   27083bff537a        331.5 MB
docker-orchagent-brcm      latest                           0ba3d931b6de        260.6 MB
docker-orchagent-brcm      master.0-dirty-20180308.064647   0ba3d931b6de        260.6 MB
docker-teamd               latest                           f0a34c57179d        257.7 MB
docker-teamd               master.0-dirty-20180308.064647   f0a34c57179d        257.7 MB
docker-fpm-quagga          latest                           3a82241badee        264.2 MB
docker-fpm-quagga          master.0-dirty-20180308.064647   3a82241badee        264.2 MB
docker-lldp-sv2            latest                           c0aa719e713e        257.1 MB
docker-lldp-sv2            master.0-dirty-20180308.064647   c0aa719e713e        257.1 MB
docker-dhcp-relay          latest                           b84f685f9202        253.7 MB
docker-dhcp-relay          master.0-dirty-20180308.064647   b84f685f9202        253.7 MB
docker-database            latest                           e43789ae68d8        252.3 MB
docker-database            master.0-dirty-20180308.064647   e43789ae68d8        252.3 MB
docker-snmp-sv2            latest                           d27771176141        292.1 MB
docker-snmp-sv2            master.0-dirty-20180308.064647   d27771176141        292.1 MB
docker-router-advertiser   latest                           fdcecc0b4bbc        250 MB
docker-router-advertiser   master.0-dirty-20180308.064647   fdcecc0b4bbc        250 MB
docker-platform-monitor    latest                           25638bff69a7        271.9 MB
docker-platform-monitor    master.0-dirty-20180308.064647   25638bff69a7        271.9 MB

**Comment by pollyhsu2git** [comment] 2018-03-16 07:37
@appleCh,
We are having the same issue on the EdgeCore AS5712-54X platform here~ Could you tell us what platform you were reporting?

**Comment by appleCh** [comment] 2018-03-20 08:19
@pollyhsu2git 
We use BCM56970 ( Tomahawk2), Configure as 64 x 100G ports.
Intel Broadwell DE CPU based.

**Comment by pollyhsu2git** [comment] 2018-03-20 08:38
@appleCh,
Thanks for your info~

**Comment by lguohan** [comment] 2018-08-21 09:36
@appleCh, I have some related to log. It looks like the problem is that we have started the bcmcmd too early. We recently added sleep in start.sh now. It should address this problem. 

I am closing this ticket, let me know if the issue still existing in current master branch.

```
Mar  9 11:22:05.145210 sonic INFO supervisord: start.sh ending connection: Success
Mar  9 11:22:05.146927 sonic ERR dsserve: _ds2tty broken pipe
Mar  9 11:22:05.149567 sonic INFO supervisord: syncd [3] _ds2tty broken pipe
```

**Closed by lguohan** 2018-08-21 09:36 UTC
