### ISSUE TITLE
front panel ports are not added to vlan bridge interface after restarting orchagent docker

### ISSUE THREAD

**Issue by lguohan** [Azure/SONiC#21] opened 2016-09-30 06:25 UTC
For Tor scanrio, where you have a vlan interface with several ports. When orchagent docker is restarted, all front panel ports are re-created, however those ports are not added back to the vlan interface.

**Comment by oleksandrivantsiv** [comment] 2016-10-06 11:53
I can't reproduce the issue. I've performed the following steps:

* Deploy configuration to device via Ansible. **vlan_interfaces** file has the following entry:
```
root@arc-switch1025:/home/admin# cat /etc/network/interfaces.d/vlan_interfaces
...
auto Vlan100
iface Vlan100 inet static
    bridge_ports Ethernet96 Ethernet100
    address 100.100.100.100
    netmask 255.255.255.0
#
root@arc-switch1025:/home/admin#
```
* Reboot device
* Verify that VLAN interface is created:
```
root@arc-switch1025:/home/admin# ip link show Vlan100
38: Vlan100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9216 qdisc noqueue state UP mode DEFAULT group default
    link/ether 00:02:03:04:05:00 brd ff:ff:ff:ff:ff:ff
root@arc-switch1025:/home/admin# ip link show Ethernet96
97: Ethernet96: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9216 qdisc pfifo_fast master Vlan100 state UP mode DEFAULT group default qlen 1000
    link/ether 00:02:03:04:05:00 brd ff:ff:ff:ff:ff:ff
root@arc-switch1025:/home/admin# ip link show Ethernet100
98: Ethernet100: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 9216 qdisc pfifo_fast master Vlan100 state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:02:03:04:05:00 brd ff:ff:ff:ff:ff:ff
```

```
journalctl -b | grep -i vlan
Oct 06 11:38:22 arc-switch1025 docker[908]: Oct 06 11:38:22 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[337]- mlnx_create_vlan: Create vlan vlan 100
Oct 06 11:38:22 arc-switch1025 docker[908]: Oct 06 11:38:22 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[504]- mlnx_create_vlan_member: Create vlan member, #0 Vlan member VID=100 #1 Vlan member port=Port,11100,000000
Oct 06 11:38:22 arc-switch1025 docker[908]: Oct 06 11:38:22 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[562]- mlnx_create_vlan_member: Created vlan member Vlan member port 11100 vlan 100
Oct 06 11:38:22 arc-switch1025 docker[908]: Oct 06 11:38:22 NOTICE  SAI_UTILS: mlnx_sai_utils.c[467]- set_dispatch_attrib_handler: Set Port Vlan ID, key:port 11100, val:100
Oct 06 11:38:22 arc-switch1025 docker[908]: Oct 06 11:38:22 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[504]- mlnx_create_vlan_member: Create vlan member, #0 Vlan member VID=100 #1 Vlan member port=Port,11300,000000
Oct 06 11:38:22 arc-switch1025 docker[908]: Oct 06 11:38:22 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[562]- mlnx_create_vlan_member: Created vlan member Vlan member port 11300 vlan 100
Oct 06 11:38:22 arc-switch1025 docker[908]: Oct 06 11:38:22 NOTICE  SAI_UTILS: mlnx_sai_utils.c[467]- set_dispatch_attrib_handler: Set Port Vlan ID, key:port 11300, val:100
Oct 06 11:38:22 arc-switch1025 docker[908]: Oct 06 11:38:22 NOTICE  SAI_RIF: mlnx_sai_rif.c[193]- mlnx_create_router_interface: Create rif, #0 Router interface virtual router ID=Virtual router,0,000000 #1 Router interface source MAC address=[00:02:03:04:05:00] #2 Router interface type=1 #3 Router interface vlan ID=100
```
* Ping host connected to one of port in VLAN interface:
```
root@arc-switch1025:/home/admin# ping 100.100.100.200
PING 100.100.100.200 (100.100.100.200) 56(84) bytes of data.
64 bytes from 100.100.100.200: icmp_seq=1 ttl=64 time=0.427 ms
64 bytes from 100.100.100.200: icmp_seq=2 ttl=64 time=0.277 ms
64 bytes from 100.100.100.200: icmp_seq=3 ttl=64 time=0.263 ms
64 bytes from 100.100.100.200: icmp_seq=4 ttl=64 time=0.335 ms
64 bytes from 100.100.100.200: icmp_seq=5 ttl=64 time=0.190 ms
^C
--- 100.100.100.200 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 3998ms
rtt min/avg/max/mdev = 0.190/0.298/0.427/0.080 ms
root@arc-switch1025:/home/admin#
```
* Restart orchagent:
```
root@arc-switch1025:/home/admin# systemctl restart orchagent
```
* Verify that after restart VLAN interface is created and all port added to VLAN:
```
journalctl -f | grep -i vlan
...
Oct 06 11:49:08 arc-switch1025 docker[2662]: Oct 06 11:49:08 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[337]- mlnx_create_vlan: Create vlan vlan 100
Oct 06 11:49:08 arc-switch1025 docker[2662]: Oct 06 11:49:08 NOTICE  SAI_RIF: mlnx_sai_rif.c[193]- mlnx_create_router_interface: Create rif, #0 Router interface virtual router ID=Virtual router,0,000000 #1 Router interface source MAC address=[00:02:03:04:05:00] #2 Router interface type=1 #3 Router interface vlan ID=100
Oct 06 11:49:41 arc-switch1025 docker[2505]: Execute command returns non-zero value! /sbin/ifup --all --force --interfaces /etc/network/interfaces.d/vlan_interfaces
Oct 06 11:49:41 arc-switch1025 docker[2662]: Oct 06 11:49:41 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[504]- mlnx_create_vlan_member: Create vlan member, #0 Vlan member VID=100 #1 Vlan member port=Port,11100,000000
Oct 06 11:49:41 arc-switch1025 docker[2662]: Oct 06 11:49:41 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[562]- mlnx_create_vlan_member: Created vlan member Vlan member port 11100 vlan 100
Oct 06 11:49:41 arc-switch1025 docker[2662]: Oct 06 11:49:41 NOTICE  SAI_UTILS: mlnx_sai_utils.c[467]- set_dispatch_attrib_handler: Set Port Vlan ID, key:port 11100, val:100
Oct 06 11:49:41 arc-switch1025 docker[2662]: Oct 06 11:49:41 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[504]- mlnx_create_vlan_member: Create vlan member, #0 Vlan member VID=100 #1 Vlan member port=Port,11300,000000
Oct 06 11:49:41 arc-switch1025 docker[2662]: Oct 06 11:49:41 NOTICE  SAI_VLAN: mlnx_sai_vlan.c[562]- mlnx_create_vlan_member: Created vlan member Vlan member port 11300 vlan 100
Oct 06 11:49:41 arc-switch1025 docker[2662]: Oct 06 11:49:41 NOTICE  SAI_UTILS: mlnx_sai_utils.c[467]- set_dispatch_attrib_handler: Set Port Vlan ID, key:port 11300, val:100
```
* Ping host connected to one of port in VLAN interface:
```
root@arc-switch1025:/home/admin# ping 100.100.100.200
PING 100.100.100.200 (100.100.100.200) 56(84) bytes of data.
64 bytes from 100.100.100.200: icmp_seq=1 ttl=64 time=0.524 ms
64 bytes from 100.100.100.200: icmp_seq=2 ttl=64 time=0.222 ms
64 bytes from 100.100.100.200: icmp_seq=3 ttl=64 time=0.231 ms
64 bytes from 100.100.100.200: icmp_seq=4 ttl=64 time=0.335 ms
64 bytes from 100.100.100.200: icmp_seq=5 ttl=64 time=0.353 ms
^C
--- 100.100.100.200 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4000ms
rtt min/avg/max/mdev = 0.222/0.333/0.524/0.109 ms
root@arc-switch1025:/home/admin#
```

Can you please provide additional information/steps how to reproduce the issue?

Thanks,
Sasha

**Comment by lguohan** [comment] 2016-10-10 15:25
@stcheng , I am not able to produce the problem. After I restart the orchagent docker on mlnx platform. I see the ports are added to Vlan233 back.

    acsadmin@str-msn2700-03:~$ sudo brctl show Vlan233
    bridge name     bridge id               STP enabled     interfaces
    Vlan233         8000.000203040500       no              Ethernet92
                                                            Ethernet96

**Comment by liatgrozovik** [comment] 2016-10-10 15:35
Can we consider this bug is fixed and close it?

**Comment by stcheng** [comment] 2016-10-10 18:38
Thanks for the verification! I'll close the issue.

**Closed by stcheng** 2016-10-10 18:38 UTC
