### ISSUE TITLE
[S6100]: Mac address for arp entry is not written in hardware

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/SONiC#126] opened 2017-11-24 06:33 UTC
Topology : T0 
Issue : 

Mac address for the arp entries are present in s/w, but not written in bcm shell. 

Mac entry for given  neighbour  address  is refected in arp , and ip neigh show  commands .

		root@sonic-s6100-01:~# arp
		
		Address                  HWtype  HWaddress           Flags Mask            Iface
		10.0.0.57                ether   52:54:00:81:57:a8   C                     PortChannel0001
		10.0.0.63                ether   52:54:00:46:6b:68   C                     PortChannel0004
		10.0.0.61                ether   52:54:00:4b:50:60   C                     PortChannel0003
		10.11.0.1                ether   00:01:e8:8b:44:71   C                     eth0
		10.0.0.59                ether   52:54:00:1d:04:ad   C                     PortChannel0002
		10.0.0.59                ether   52:54:00:1d:04:ad   C                     PortChannel0002
ip neigh show : 
		
		root@sonic-s6100-01:~# ip neigh show
		10.0.0.57 dev PortChannel0001 lladdr 52:54:00:81:57:a8 REACHABLE
		10.0.0.63 dev PortChannel0004 lladdr 52:54:00:46:6b:68 REACHABLE
		10.11.8.12 dev eth0 lladdr 00:01:e8:8b:44:71 STALE
		10.0.0.61 dev PortChannel0003 lladdr 52:54:00:4b:50:60 REACHABLE
		10.11.0.1 dev eth0 lladdr 00:01:e8:8b:44:71 STALE
		10.0.0.59 dev PortChannel0002 lladdr 52:54:00:1d:04:ad REACHABLE
		
Mac address  is written as 00:00 in bcm shell.

		
		root@sonic-s6100-01:~# bcmcmd "l3 l3table show"
		l3 l3table show
		Unit 0, free L3 table entries: 8180
		Entry VRF IP address       Mac Address           INTF MOD PORT    CLASS HIT    H/W Index
		1     0    10.0.0.63        00:00:00:00:00:00  100004    0    0         0 y      256
		2     0    10.0.0.59        00:00:00:00:00:00  100005    0    0         0 y      840
		3     0    10.0.0.61        00:00:00:00:00:00  100006    0    0         0 y      1424
		4     0    10.0.0.57        00:00:00:00:00:00  100007    0    0         0 y      2008
		
		drivshell>

PIng output : 

	root@sonic-s6100-01:~# ping 10.0.0.63
	PING 10.0.0.63 (10.0.0.63) 56(84) bytes of data.
	64 bytes from 10.0.0.63: icmp_seq=1 ttl=64 time=8.56 ms
	64 bytes from 10.0.0.63: icmp_seq=2 ttl=64 time=7.87 ms
	
	--- 10.0.0.63 ping statistics ---
	2 packets transmitted, 2 received, 0% packet loss, time 999ms
	rtt min/avg/max/mdev = 7.872/8.217/8.563/0.357 ms
	
	root@sonic-s6100-01:~# ping 10.0.0.59
	PING 10.0.0.59 (10.0.0.59) 56(84) bytes of data.
	64 bytes from 10.0.0.59: icmp_seq=1 ttl=64 time=10.5 ms
	64 bytes from 10.0.0.59: icmp_seq=2 ttl=64 time=8.28 ms
	
	--- 10.0.0.59 ping statistics ---
	2 packets transmitted, 2 received, 0% packet loss, time 1001ms
	rtt min/avg/max/mdev = 8.286/9.440/10.595/1.158 ms
	
	root@sonic-s6100-01:~# ping 10.0.0.57
	PING 10.0.0.57 (10.0.0.57) 56(84) bytes of data.
	64 bytes from 10.0.0.57: icmp_seq=1 ttl=64 time=8.82 ms
	64 bytes from 10.0.0.57: icmp_seq=2 ttl=64 time=9.63 ms
	
	--- 10.0.0.57 ping statistics ---
	2 packets transmitted, 2 received, 0% packet loss, time 1001ms
	rtt min/avg/max/mdev = 8.827/9.233/9.639/0.406 ms
	
	root@sonic-s6100-01:~# ping 10.0.0.61
	PING 10.0.0.61 (10.0.0.61) 56(84) bytes of data.
	64 bytes from 10.0.0.61: icmp_seq=1 ttl=64 time=7.57 ms
	64 bytes from 10.0.0.61: icmp_seq=2 ttl=64 time=7.91 ms
	
	--- 10.0.0.61 ping statistics ---
	2 packets transmitted, 2 received, 0% packet loss, time 1001ms
	rtt min/avg/max/mdev = 7.579/7.747/7.916/0.190 ms
	root@sonic-s6100-01:~#

**Comment by lguohan** [comment] 2017-11-28 16:55
can you check the l3 egress show, the l3 egress object has the mac address.

**Comment by prsunny** [comment] 2017-11-28 17:07
The mac-address is programmed in the l3 egress table. Also the functionality (ping) is found to be working here. I think, this can be marked as an expected behavior since BCM shows mac-address as 00 in "l3 l3table" output but is actually programmed in the "l3 egress" tables

admin@str-z9100-acs-2:~$ bcmcmd 'l3 egress show' (Output from my t0 testbed)
l3 egress show
Entry  Mac                 Vlan INTF PORT MOD MPLS_LABEL ToCpu Drop RefCount L3MC
100004  52:54:00:28:c1:52 4094    1     0t   0        -1   no   no    3   no
100005  52:54:00:28:c1:52 4094    1     0t   0        -1   no   no    3   no
100006  52:54:00:cf:2a:bd 4093    2     1t   0        -1   no   no    3   no
100007  52:54:00:cf:2a:bd 4093    2     1t   0        -1   no   no    3   no
100008  52:54:00:f7:53:0c 4092    3     2t   0        -1   no   no    3   no

**Comment by pavel-shirshov** [comment] 2017-11-28 22:14
I've opened a CSP case with Broadcom. I'll update the thread as they respond.
As I remember they previously mentioned that they don't populate ports entries in "l3 l3tables"
Probably they do the same with mac entries.

**Comment by pavel-shirshov** [comment] 2017-11-30 02:01
Answer from Broadcom
```
This is for a special case in TH device, When the L3 interface is a LAG then a reference to a next hop object is used and the mac is only available in the corresponding L3 egress entry.
Its working as designed.
```
So it's not a bug.
Closing

**Closed by pavel-shirshov** 2017-11-30 02:01 UTC
Labels: bug, question
